#!/usr/bin/env python3
"""Generate each repository's no-RAG baseline config from its RAG config.

The no-RAG baseline must differ from the RAG config in exactly one respect: every
`enabled` flag inside a `rag:` / `rag_config:` block is false. Anything else —
rules_text, priorities, llm settings, impact analysis — has to stay byte-identical,
otherwise a RAG vs no-RAG comparison measures the config difference as well as
retrieval. (The hand-maintained baselines for home-assistant and vscode had drifted
badly: they also dropped whole rule blocks and shortened many rules_text bodies.)

Usage:
    python exp/sync_no_rag_config.py            # all repos under exp/
    python exp/sync_no_rag_config.py vscode     # one repo
    python exp/sync_no_rag_config.py --check    # verify, write nothing (exit 1 on drift)

Rewriting is done line-wise rather than by loading and re-dumping YAML on purpose:
a round-trip through a YAML library reformats the block scalars that carry the
review rules, which would change the prompt the model sees.
"""
from __future__ import annotations

import sys
from pathlib import Path

EXP_DIR = Path(__file__).parent
RAG_BLOCK_KEYS = ("rag:", "rag_config:")

REPO_TITLES = {
    "home-assistant": "home-assistant/core",
    "sentry": "getsentry/sentry",
    "vscode": "microsoft/vscode",
}


def _indent_of(line: str) -> int:
    return len(line) - len(line.lstrip(" \t"))


def to_no_rag(text: str, repo: str) -> str:
    """Return the no-RAG variant of a config: rag `enabled` flags flipped to false."""
    lines = text.split("\n")
    out: list[str] = []
    rag_block_indent: int | None = None

    for line in lines:
        stripped = line.strip()

        # Leaving the rag block? (a non-blank line at or left of its own indent)
        if rag_block_indent is not None and stripped and not stripped.startswith("#"):
            if _indent_of(line) <= rag_block_indent:
                rag_block_indent = None

        # Entering a rag block?
        if stripped in RAG_BLOCK_KEYS or stripped.lstrip("- ") in RAG_BLOCK_KEYS:
            rag_block_indent = _indent_of(line)
            out.append(line)
            continue

        if rag_block_indent is not None and stripped == "enabled: true":
            out.append(line.replace("enabled: true", "enabled: false"))
            continue

        out.append(line)

    body = "\n".join(out)

    # Replace the leading comment block with a generated-file header.
    body_lines = body.split("\n")
    first_non_comment = next(
        (i for i, l in enumerate(body_lines) if l.strip() and not l.lstrip().startswith("#")),
        0,
    )
    header = [
        f"# ACR Configuration for {REPO_TITLES.get(repo, repo)} — NO RAG variant",
        f"# GENERATED by exp/sync_no_rag_config.py from .acr-config.yml — do not edit by hand.",
        "# Identical to .acr-config.yml except that every rag `enabled` flag is false, so",
        "# that any RAG vs no-RAG difference is attributable to retrieval alone.",
    ]
    return "\n".join(header + body_lines[first_non_comment:])


def main(argv: list[str]) -> int:
    check_only = "--check" in argv
    repos = [a for a in argv if not a.startswith("-")] or sorted(REPO_TITLES)

    drift = False
    for repo in repos:
        src = EXP_DIR / repo / ".acr-config.yml"
        dst = EXP_DIR / repo / ".acr-config-no-rag.yml"
        if not src.is_file():
            print(f"skip {repo}: {src} not found", file=sys.stderr)
            continue

        expected = to_no_rag(src.read_text(encoding="utf-8"), repo)
        current = dst.read_text(encoding="utf-8") if dst.is_file() else None

        if current == expected:
            print(f"{repo}: up to date")
            continue

        drift = True
        if check_only:
            print(f"{repo}: DRIFT — {dst} differs from what {src} generates")
        else:
            dst.write_text(expected, encoding="utf-8")
            print(f"{repo}: regenerated {dst}")

    return 1 if (check_only and drift) else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
